//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets3B6352FCB23A4F3DE4267B3D09A95F1C8179E39792C1B49FF8CCCB7DE4B82FB9))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// 此类型包含在设计时生成的 EntitySets 和 AssociationSets 的视图。
    /// </Summary>
    public sealed class ViewsForBaseEntitySets3B6352FCB23A4F3DE4267B3D09A95F1C8179E39792C1B49FF8CCCB7DE4B82FB9 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// 构造函数存储各区的视图，以及根据元数据和映射结束和视图生成的哈希值。
        /// </Summary>
        public ViewsForBaseEntitySets3B6352FCB23A4F3DE4267B3D09A95F1C8179E39792C1B49FF8CCCB7DE4B82FB9()
        {
            this.EdmEntityContainerName = "EF_EMREntities";
            this.StoreEntityContainerName = "EF_EMRModelStoreContainer";
            this.HashOverMappingClosure = "bb32190cce874f5b78f7ae2a71a733da6bd0c26a21c0784753578376c3b15a67";
            this.HashOverAllExtentViews = "69f80ca13ad573ce91867fc25a3c0d911074dc880253a1c0bd9d87e4eb7b6835";
            this.ViewCount = 4;
        }
        
        /// <Summary>
        /// 此方法返回给定索引的视图。
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// 返回 EF_EMRModelStoreContainer.PAT_MASTER_INDEX 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2890);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PAT_MASTER_INDEX\r\n        [EF_EMRModel.Store.");
            viewString.Append("PAT_MASTER_INDEX](T1.[PAT_MASTER_INDEX.PATIENT_ID], T1.[PAT_MASTER_INDEX.INP_NO]");
            viewString.Append(", T1.[PAT_MASTER_INDEX.NAME], T1.[PAT_MASTER_INDEX.NAME_PHONETIC], T1.[PAT_MASTE");
            viewString.Append("R_INDEX.SEX], T1.[PAT_MASTER_INDEX.DATE_OF_BIRTH], T1.[PAT_MASTER_INDEX.BIRTH_PL");
            viewString.Append("ACE], T1.[PAT_MASTER_INDEX.CITIZENSHIP], T1.[PAT_MASTER_INDEX.NATION], T1.[PAT_M");
            viewString.Append("ASTER_INDEX.ID_NO], T1.[PAT_MASTER_INDEX.IDENTITY], T1.[PAT_MASTER_INDEX.CHARGE_");
            viewString.Append("TYPE], T1.[PAT_MASTER_INDEX.UNIT_IN_CONTRACT], T1.[PAT_MASTER_INDEX.MAILING_ADDR");
            viewString.Append("ESS], T1.[PAT_MASTER_INDEX.ZIP_CODE], T1.[PAT_MASTER_INDEX.PHONE_NUMBER_HOME], T");
            viewString.Append("1.[PAT_MASTER_INDEX.PHONE_NUMBER_BUSINESS], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN], T");
            viewString.Append("1.[PAT_MASTER_INDEX.RELATIONSHIP], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN_ADDR], T1.[P");
            viewString.Append("AT_MASTER_INDEX.NEXT_OF_KIN_ZIP_CODE], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN_PHONE], ");
            viewString.Append("T1.[PAT_MASTER_INDEX.LAST_VISIT_DATE], T1.[PAT_MASTER_INDEX.VIP_INDICATOR], T1.[");
            viewString.Append("PAT_MASTER_INDEX.CREATE_DATE], T1.[PAT_MASTER_INDEX.OPERATOR], T1.[PAT_MASTER_IN");
            viewString.Append("DEX.myid])\r\n    FROM (\r\n        SELECT \r\n            T.PATIENT_ID AS [PAT_MASTER");
            viewString.Append("_INDEX.PATIENT_ID], \r\n            T.INP_NO AS [PAT_MASTER_INDEX.INP_NO], \r\n     ");
            viewString.Append("       T.NAME AS [PAT_MASTER_INDEX.NAME], \r\n            T.NAME_PHONETIC AS [PAT_");
            viewString.Append("MASTER_INDEX.NAME_PHONETIC], \r\n            T.SEX AS [PAT_MASTER_INDEX.SEX], \r\n  ");
            viewString.Append("          T.DATE_OF_BIRTH AS [PAT_MASTER_INDEX.DATE_OF_BIRTH], \r\n            T.B");
            viewString.Append("IRTH_PLACE AS [PAT_MASTER_INDEX.BIRTH_PLACE], \r\n            T.CITIZENSHIP AS [PA");
            viewString.Append("T_MASTER_INDEX.CITIZENSHIP], \r\n            T.NATION AS [PAT_MASTER_INDEX.NATION]");
            viewString.Append(", \r\n            T.ID_NO AS [PAT_MASTER_INDEX.ID_NO], \r\n            T.IDENTITY AS");
            viewString.Append(" [PAT_MASTER_INDEX.IDENTITY], \r\n            T.CHARGE_TYPE AS [PAT_MASTER_INDEX.C");
            viewString.Append("HARGE_TYPE], \r\n            T.UNIT_IN_CONTRACT AS [PAT_MASTER_INDEX.UNIT_IN_CONTR");
            viewString.Append("ACT], \r\n            T.MAILING_ADDRESS AS [PAT_MASTER_INDEX.MAILING_ADDRESS], \r\n ");
            viewString.Append("           T.ZIP_CODE AS [PAT_MASTER_INDEX.ZIP_CODE], \r\n            T.PHONE_NUMB");
            viewString.Append("ER_HOME AS [PAT_MASTER_INDEX.PHONE_NUMBER_HOME], \r\n            T.PHONE_NUMBER_BU");
            viewString.Append("SINESS AS [PAT_MASTER_INDEX.PHONE_NUMBER_BUSINESS], \r\n            T.NEXT_OF_KIN ");
            viewString.Append("AS [PAT_MASTER_INDEX.NEXT_OF_KIN], \r\n            T.[RELATIONSHIP] AS [PAT_MASTER");
            viewString.Append("_INDEX.RELATIONSHIP], \r\n            T.NEXT_OF_KIN_ADDR AS [PAT_MASTER_INDEX.NEXT");
            viewString.Append("_OF_KIN_ADDR], \r\n            T.NEXT_OF_KIN_ZIP_CODE AS [PAT_MASTER_INDEX.NEXT_OF");
            viewString.Append("_KIN_ZIP_CODE], \r\n            T.NEXT_OF_KIN_PHONE AS [PAT_MASTER_INDEX.NEXT_OF_K");
            viewString.Append("IN_PHONE], \r\n            T.LAST_VISIT_DATE AS [PAT_MASTER_INDEX.LAST_VISIT_DATE]");
            viewString.Append(", \r\n            T.VIP_INDICATOR AS [PAT_MASTER_INDEX.VIP_INDICATOR], \r\n         ");
            viewString.Append("   T.CREATE_DATE AS [PAT_MASTER_INDEX.CREATE_DATE], \r\n            T.OPERATOR AS ");
            viewString.Append("[PAT_MASTER_INDEX.OPERATOR], \r\n            T.myid AS [PAT_MASTER_INDEX.myid], \r\n");
            viewString.Append("            True AS _from0\r\n        FROM EF_EMREntities.PAT_MASTER_INDEX AS T\r\n ");
            viewString.Append("   ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("EF_EMRModelStoreContainer.PAT_MASTER_INDEX", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 EF_EMREntities.PAT_MASTER_INDEX 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2895);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PAT_MASTER_INDEX\r\n        [EF_EMRModel.PAT_MA");
            viewString.Append("STER_INDEX](T1.[PAT_MASTER_INDEX.PATIENT_ID], T1.[PAT_MASTER_INDEX.INP_NO], T1.[");
            viewString.Append("PAT_MASTER_INDEX.NAME], T1.[PAT_MASTER_INDEX.NAME_PHONETIC], T1.[PAT_MASTER_INDE");
            viewString.Append("X.SEX], T1.[PAT_MASTER_INDEX.DATE_OF_BIRTH], T1.[PAT_MASTER_INDEX.BIRTH_PLACE], ");
            viewString.Append("T1.[PAT_MASTER_INDEX.CITIZENSHIP], T1.[PAT_MASTER_INDEX.NATION], T1.[PAT_MASTER_");
            viewString.Append("INDEX.ID_NO], T1.[PAT_MASTER_INDEX.IDENTITY], T1.[PAT_MASTER_INDEX.CHARGE_TYPE],");
            viewString.Append(" T1.[PAT_MASTER_INDEX.UNIT_IN_CONTRACT], T1.[PAT_MASTER_INDEX.MAILING_ADDRESS], ");
            viewString.Append("T1.[PAT_MASTER_INDEX.ZIP_CODE], T1.[PAT_MASTER_INDEX.PHONE_NUMBER_HOME], T1.[PAT");
            viewString.Append("_MASTER_INDEX.PHONE_NUMBER_BUSINESS], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN], T1.[PAT");
            viewString.Append("_MASTER_INDEX.RELATIONSHIP], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN_ADDR], T1.[PAT_MAS");
            viewString.Append("TER_INDEX.NEXT_OF_KIN_ZIP_CODE], T1.[PAT_MASTER_INDEX.NEXT_OF_KIN_PHONE], T1.[PA");
            viewString.Append("T_MASTER_INDEX.LAST_VISIT_DATE], T1.[PAT_MASTER_INDEX.VIP_INDICATOR], T1.[PAT_MA");
            viewString.Append("STER_INDEX.CREATE_DATE], T1.[PAT_MASTER_INDEX.OPERATOR], T1.[PAT_MASTER_INDEX.my");
            viewString.Append("id])\r\n    FROM (\r\n        SELECT \r\n            T.PATIENT_ID AS [PAT_MASTER_INDEX");
            viewString.Append(".PATIENT_ID], \r\n            T.INP_NO AS [PAT_MASTER_INDEX.INP_NO], \r\n           ");
            viewString.Append(" T.NAME AS [PAT_MASTER_INDEX.NAME], \r\n            T.NAME_PHONETIC AS [PAT_MASTER");
            viewString.Append("_INDEX.NAME_PHONETIC], \r\n            T.SEX AS [PAT_MASTER_INDEX.SEX], \r\n        ");
            viewString.Append("    T.DATE_OF_BIRTH AS [PAT_MASTER_INDEX.DATE_OF_BIRTH], \r\n            T.BIRTH_P");
            viewString.Append("LACE AS [PAT_MASTER_INDEX.BIRTH_PLACE], \r\n            T.CITIZENSHIP AS [PAT_MAST");
            viewString.Append("ER_INDEX.CITIZENSHIP], \r\n            T.NATION AS [PAT_MASTER_INDEX.NATION], \r\n  ");
            viewString.Append("          T.ID_NO AS [PAT_MASTER_INDEX.ID_NO], \r\n            T.IDENTITY AS [PAT_");
            viewString.Append("MASTER_INDEX.IDENTITY], \r\n            T.CHARGE_TYPE AS [PAT_MASTER_INDEX.CHARGE_");
            viewString.Append("TYPE], \r\n            T.UNIT_IN_CONTRACT AS [PAT_MASTER_INDEX.UNIT_IN_CONTRACT], ");
            viewString.Append("\r\n            T.MAILING_ADDRESS AS [PAT_MASTER_INDEX.MAILING_ADDRESS], \r\n       ");
            viewString.Append("     T.ZIP_CODE AS [PAT_MASTER_INDEX.ZIP_CODE], \r\n            T.PHONE_NUMBER_HOM");
            viewString.Append("E AS [PAT_MASTER_INDEX.PHONE_NUMBER_HOME], \r\n            T.PHONE_NUMBER_BUSINESS");
            viewString.Append(" AS [PAT_MASTER_INDEX.PHONE_NUMBER_BUSINESS], \r\n            T.NEXT_OF_KIN AS [PA");
            viewString.Append("T_MASTER_INDEX.NEXT_OF_KIN], \r\n            T.[RELATIONSHIP] AS [PAT_MASTER_INDEX");
            viewString.Append(".RELATIONSHIP], \r\n            T.NEXT_OF_KIN_ADDR AS [PAT_MASTER_INDEX.NEXT_OF_KI");
            viewString.Append("N_ADDR], \r\n            T.NEXT_OF_KIN_ZIP_CODE AS [PAT_MASTER_INDEX.NEXT_OF_KIN_Z");
            viewString.Append("IP_CODE], \r\n            T.NEXT_OF_KIN_PHONE AS [PAT_MASTER_INDEX.NEXT_OF_KIN_PHO");
            viewString.Append("NE], \r\n            T.LAST_VISIT_DATE AS [PAT_MASTER_INDEX.LAST_VISIT_DATE], \r\n  ");
            viewString.Append("          T.VIP_INDICATOR AS [PAT_MASTER_INDEX.VIP_INDICATOR], \r\n            T.C");
            viewString.Append("REATE_DATE AS [PAT_MASTER_INDEX.CREATE_DATE], \r\n            T.OPERATOR AS [PAT_M");
            viewString.Append("ASTER_INDEX.OPERATOR], \r\n            T.myid AS [PAT_MASTER_INDEX.myid], \r\n      ");
            viewString.Append("      True AS _from0\r\n        FROM EF_EMRModelStoreContainer.PAT_MASTER_INDEX AS");
            viewString.Append(" T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("EF_EMREntities.PAT_MASTER_INDEX", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 EF_EMRModelStoreContainer.PAT_VISIT 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(16186);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PAT_VISIT\r\n        [EF_EMRModel.Store.PAT_VIS");
            viewString.Append("IT](T1.[PAT_VISIT.PATIENT_ID], T1.[PAT_VISIT.VISIT_ID], T1.[PAT_VISIT.DEPT_ADMIS");
            viewString.Append("SION_TO], T1.[PAT_VISIT.ADMISSION_DATE_TIME], T1.[PAT_VISIT.DEPT_DISCHARGE_FROM]");
            viewString.Append(", T1.[PAT_VISIT.DISCHARGE_DATE_TIME], T1.[PAT_VISIT.OCCUPATION], T1.[PAT_VISIT.M");
            viewString.Append("ARITAL_STATUS], T1.[PAT_VISIT.IDENTITY], T1.[PAT_VISIT.ARMED_SERVICES], T1.[PAT_");
            viewString.Append("VISIT.DUTY], T1.[PAT_VISIT.UNIT_IN_CONTRACT], T1.[PAT_VISIT.CHARGE_TYPE], T1.[PA");
            viewString.Append("T_VISIT.INSURANCE_TYPE], T1.[PAT_VISIT.INSURANCE_NO], T1.[PAT_VISIT.SERVICE_AGEN");
            viewString.Append("CY], T1.[PAT_VISIT.MAILING_ADDRESS], T1.[PAT_VISIT.ZIP_CODE], T1.[PAT_VISIT.NEXT");
            viewString.Append("_OF_KIN], T1.[PAT_VISIT.RELATIONSHIP], T1.[PAT_VISIT.NEXT_OF_KIN_ADDR], T1.[PAT_");
            viewString.Append("VISIT.NEXT_OF_KIN_ZIPCODE], T1.[PAT_VISIT.NEXT_OF_KIN_PHONE], T1.[PAT_VISIT.PATI");
            viewString.Append("ENT_CLASS], T1.[PAT_VISIT.ADMISSION_CAUSE], T1.[PAT_VISIT.CONSULTING_DATE], T1.[");
            viewString.Append("PAT_VISIT.PAT_ADM_CONDITION], T1.[PAT_VISIT.CONSULTING_DOCTOR], T1.[PAT_VISIT.AD");
            viewString.Append("MITTED_BY], T1.[PAT_VISIT.EMER_TREAT_TIMES], T1.[PAT_VISIT.ESC_EMER_TIMES], T1.[");
            viewString.Append("PAT_VISIT.SPEC_LEVEL_NURS_DAYS], T1.[PAT_VISIT.FIRST_LEVEL_NURS_DAYS], T1.[PAT_V");
            viewString.Append("ISIT.AUTOPSY_INDICATOR], T1.[PAT_VISIT.BLOOD_TYPE], T1.[PAT_VISIT.BLOOD_TRAN_TIM");
            viewString.Append("ES], T1.[PAT_VISIT.BLOOD_TRAN_VOL], T1.[PAT_VISIT.BLOOD_TRAN_REACT_TIMES], T1.[P");
            viewString.Append("AT_VISIT.ALERGY_DRUGS], T1.[PAT_VISIT.MR_VALUE], T1.[PAT_VISIT.MR_QUALITY], T1.[");
            viewString.Append("PAT_VISIT.FOLLOW_INDICATOR], T1.[PAT_VISIT.FOLLOW_INTERVAL], T1.[PAT_VISIT.FOLLO");
            viewString.Append("W_INTERVAL_UNITS], T1.[PAT_VISIT.DIRECTOR], T1.[PAT_VISIT.ATTENDING_DOCTOR], T1.");
            viewString.Append("[PAT_VISIT.DOCTOR_IN_CHARGE], T1.[PAT_VISIT.DISCHARGE_DISPOSITION], T1.[PAT_VISI");
            viewString.Append("T.TOTAL_COSTS], T1.[PAT_VISIT.TOTAL_PAYMENTS], T1.[PAT_VISIT.CATALOG_DATE], T1.[");
            viewString.Append("PAT_VISIT.CATALOGER], T1.[PAT_VISIT.WORKING_STSTUS], T1.[PAT_VISIT.SERIOUS_COND_");
            viewString.Append("DAYS], T1.[PAT_VISIT.CRITICAL_COND_DAYS], T1.[PAT_VISIT.ICU_DAYS], T1.[PAT_VISIT");
            viewString.Append(".CCU_DAYS], T1.[PAT_VISIT.SECOND_LEVEL_NURS_DAYS], T1.[PAT_VISIT.INFUSION_REACT_");
            viewString.Append("TIMES], T1.[PAT_VISIT.DECUBITAL_ULCER_TIMES], T1.[PAT_VISIT.WORKING_STATUS], T1.");
            viewString.Append("[PAT_VISIT.BLOOD_TYPE_RH], T1.[PAT_VISIT.ADVERSE_REACTION_DRUGS], T1.[PAT_VISIT.");
            viewString.Append("TOP_UNIT], T1.[PAT_VISIT.SERVICE_SYSTEM_INDICATOR], T1.[PAT_VISIT.HEALTH_LEVEL],");
            viewString.Append(" T1.[PAT_VISIT.MR_INFECT_REPORT], T1.[PAT_VISIT.INFECT_INDICATOR], T1.[PAT_VISIT");
            viewString.Append(".MR_BACK_DATE_TIME], T1.[PAT_VISIT.MR_BACK_MAN], T1.[PAT_VISIT.BODY_WEIGHT], T1.");
            viewString.Append("[PAT_VISIT.BODY_HEIGHT], T1.[PAT_VISIT.INTERNAL_NO], T1.[PAT_VISIT.IDENTITY_CLAS");
            viewString.Append("S], T1.[PAT_VISIT.HBSAG_INDICATOR], T1.[PAT_VISIT.HCV_AB_INDICATOR], T1.[PAT_VIS");
            viewString.Append("IT.HIV_AB_INDICATOR], T1.[PAT_VISIT.CHIEF_DOCTOR], T1.[PAT_VISIT.ADVANCED_STUDIE");
            viewString.Append("S_DOCTOR], T1.[PAT_VISIT.PRACTICE_DOCTOR_OF_GRADUATE], T1.[PAT_VISIT.PRACTICE_DO");
            viewString.Append("CTOR], T1.[PAT_VISIT.DOCTOR_OF_CONTROL_QUALITY], T1.[PAT_VISIT.NURSE_OF_CONTROL_");
            viewString.Append("QUALITY], T1.[PAT_VISIT.DATE_OF_CONTROL_QUALITY], T1.[PAT_VISIT.FIRST_CASE_INDIC");
            viewString.Append("ATOR], T1.[PAT_VISIT.THIRD_LEVEL_NURS_DAYS], T1.[PAT_VISIT.X_EXAM_NO], T1.[PAT_V");
            viewString.Append("ISIT.MEDICAL_PAY_WAY], T1.[PAT_VISIT.FIRST_AID_INDICATOR], T1.[PAT_VISIT.MTD_VAL");
            viewString.Append("UE], T1.[PAT_VISIT.REQUEST_DOCTOR_ID], T1.[PAT_VISIT.PARENT_DOCTOR_ID], T1.[PAT_");
            viewString.Append("VISIT.SUPER_DOCTOR_ID], T1.[PAT_VISIT.BED_LABEL], T1.[PAT_VISIT.BED_NO], T1.[PAT");
            viewString.Append("_VISIT.DIAGNOSIS_DATE], T1.[PAT_VISIT.MR_SCORE], T1.[PAT_VISIT.PAPER_MR_RECEIVE_");
            viewString.Append("DATE], T1.[PAT_VISIT.PAPER_MR_OFFSET_DAYS], T1.[PAT_VISIT.BED_ADMISSION_TO], T1.");
            viewString.Append("[PAT_VISIT.BED_DISCHARGE_FROM], T1.[PAT_VISIT.PAPER_MR_RECEIVE_OPER_DATE], T1.[P");
            viewString.Append("AT_VISIT.PAPER_MR_RECEIVE_OPERATOR], T1.[PAT_VISIT.PAPER_MR_RECEIVE_NURSE], T1.[");
            viewString.Append("PAT_VISIT.PAPER_MR_RECEIVE_NURSE_DATE], T1.[PAT_VISIT.PAPER_MR_RETURNER], T1.[PA");
            viewString.Append("T_VISIT.CLINIC_TYPE], T1.[PAT_VISIT.CLINIC_VISIT_NO], T1.[PAT_VISIT.CLINIC_REGIS");
            viewString.Append("TRY_STATUS], T1.[PAT_VISIT.CLINIC_DOCTOR_ID], T1.[PAT_VISIT.GH_DATE], T1.[PAT_VI");
            viewString.Append("SIT.GH_DEPT_CODE], T1.[PAT_VISIT.GH_OPERATOR], T1.[PAT_VISIT.THREE_DAY_DIAGNOSIS");
            viewString.Append("_CODE], T1.[PAT_VISIT.THREE_DAY_DIAGNOSIS_NAME], T1.[PAT_VISIT.THREE_DAY_DIAGNOS");
            viewString.Append("IS_REASON], T1.[PAT_VISIT.MR_DOCTOR_PART_STATUS], T1.[PAT_VISIT.MR_NURSE_PART_ST");
            viewString.Append("ATUS], T1.[PAT_VISIT.IN_CONSULT_TIMES], T1.[PAT_VISIT.FAR_CONSULT_TIMES], T1.[PA");
            viewString.Append("T_VISIT.BABY_FLAG], T1.[PAT_VISIT.WARD_ADMISSION_TO], T1.[PAT_VISIT.WARD_DISCHAR");
            viewString.Append("GE_FROM], T1.[PAT_VISIT.INP_NO], T1.[PAT_VISIT.MR_NURSE_SCORE], T1.[PAT_VISIT.MR");
            viewString.Append("_DOCTOR_SCORE], T1.[PAT_VISIT.WARD_DATE_TIME], T1.[PAT_VISIT.PAPER_MR_RECEIVER],");
            viewString.Append(" T1.[PAT_VISIT.FOLLOW_OVER_DATE_TIME], T1.[PAT_VISIT.MRQC_DOCT_ID], T1.[PAT_VISI");
            viewString.Append("T.MRQC_DOCT_DATE_TIME], T1.[PAT_VISIT.DIRECTOR_ID], T1.[PAT_VISIT.CHIEF_DOCTOR_I");
            viewString.Append("D], T1.[PAT_VISIT.ATTENDING_DOCTOR_ID], T1.[PAT_VISIT.DOCTOR_IN_CHARGE_ID], T1.[");
            viewString.Append("PAT_VISIT.ADVANCED_STUDIES_DOCTOR_ID], T1.[PAT_VISIT.PRACTICE_DOCTOR_ID], T1.[PA");
            viewString.Append("T_VISIT.PRACTICE_DOCTOR_OF_GRADUATE_ID], T1.[PAT_VISIT.DEATH_DATE_TIME], T1.[PAT");
            viewString.Append("_VISIT.IN_CP_DATE], T1.[PAT_VISIT.IN_CP_USER_ID], T1.[PAT_VISIT.CP_STATUS], T1.[");
            viewString.Append("PAT_VISIT.CP_ID], T1.[PAT_VISIT.OUT_CP_DATE], T1.[PAT_VISIT.IN_CP_DAYS], T1.[PAT");
            viewString.Append("_VISIT.THREE_DAY_OPERATION], T1.[PAT_VISIT.ALERGY_DRUGS1], T1.[PAT_VISIT.INP_NO_");
            viewString.Append("ALIAS], T1.[PAT_VISIT.CP_MEMO], T1.[PAT_VISIT.CP_EXCLUDE_ID], T1.[PAT_VISIT.CP_E");
            viewString.Append("XCLUDE_NAME], T1.[PAT_VISIT.CLINICAL_PATHWAY], T1.[PAT_VISIT.PAT_ORIGIN], T1.[PA");
            viewString.Append("T_VISIT.X_CT_NO], T1.[PAT_VISIT.X_MRI_NO], T1.[PAT_VISIT.X_TUMOUR_CARD], T1.[PAT");
            viewString.Append("_VISIT.X_CONTAGION_CARD], T1.[PAT_VISIT.BA_VISIT_ID], T1.[PAT_VISIT.PHONE_MAILIN");
            viewString.Append("G_ADDRESS], T1.[PAT_VISIT.X_Xshexian_NO], T1.[PAT_VISIT.dept_transfer], T1.[PAT_");
            viewString.Append("VISIT.ShuxuePinzhong], T1.[PAT_VISIT.PAT_AGE], T1.[PAT_VISIT.PAT_BIRTHDAY_BABY],");
            viewString.Append(" T1.[PAT_VISIT.NURSE_GROUP_NO], T1.[PAT_VISIT.myID])\r\n    FROM (\r\n        SELECT");
            viewString.Append(" \r\n            T.PATIENT_ID AS [PAT_VISIT.PATIENT_ID], \r\n            T.VISIT_ID ");
            viewString.Append("AS [PAT_VISIT.VISIT_ID], \r\n            T.DEPT_ADMISSION_TO AS [PAT_VISIT.DEPT_AD");
            viewString.Append("MISSION_TO], \r\n            T.ADMISSION_DATE_TIME AS [PAT_VISIT.ADMISSION_DATE_TI");
            viewString.Append("ME], \r\n            T.DEPT_DISCHARGE_FROM AS [PAT_VISIT.DEPT_DISCHARGE_FROM], \r\n ");
            viewString.Append("           T.DISCHARGE_DATE_TIME AS [PAT_VISIT.DISCHARGE_DATE_TIME], \r\n         ");
            viewString.Append("   T.OCCUPATION AS [PAT_VISIT.OCCUPATION], \r\n            T.MARITAL_STATUS AS [PA");
            viewString.Append("T_VISIT.MARITAL_STATUS], \r\n            T.IDENTITY AS [PAT_VISIT.IDENTITY], \r\n   ");
            viewString.Append("         T.ARMED_SERVICES AS [PAT_VISIT.ARMED_SERVICES], \r\n            T.DUTY AS");
            viewString.Append(" [PAT_VISIT.DUTY], \r\n            T.UNIT_IN_CONTRACT AS [PAT_VISIT.UNIT_IN_CONTRA");
            viewString.Append("CT], \r\n            T.CHARGE_TYPE AS [PAT_VISIT.CHARGE_TYPE], \r\n            T.INS");
            viewString.Append("URANCE_TYPE AS [PAT_VISIT.INSURANCE_TYPE], \r\n            T.INSURANCE_NO AS [PAT_");
            viewString.Append("VISIT.INSURANCE_NO], \r\n            T.SERVICE_AGENCY AS [PAT_VISIT.SERVICE_AGENCY");
            viewString.Append("], \r\n            T.MAILING_ADDRESS AS [PAT_VISIT.MAILING_ADDRESS], \r\n           ");
            viewString.Append(" T.ZIP_CODE AS [PAT_VISIT.ZIP_CODE], \r\n            T.NEXT_OF_KIN AS [PAT_VISIT.N");
            viewString.Append("EXT_OF_KIN], \r\n            T.[RELATIONSHIP] AS [PAT_VISIT.RELATIONSHIP], \r\n     ");
            viewString.Append("       T.NEXT_OF_KIN_ADDR AS [PAT_VISIT.NEXT_OF_KIN_ADDR], \r\n            T.NEXT_");
            viewString.Append("OF_KIN_ZIPCODE AS [PAT_VISIT.NEXT_OF_KIN_ZIPCODE], \r\n            T.NEXT_OF_KIN_P");
            viewString.Append("HONE AS [PAT_VISIT.NEXT_OF_KIN_PHONE], \r\n            T.PATIENT_CLASS AS [PAT_VIS");
            viewString.Append("IT.PATIENT_CLASS], \r\n            T.ADMISSION_CAUSE AS [PAT_VISIT.ADMISSION_CAUSE");
            viewString.Append("], \r\n            T.CONSULTING_DATE AS [PAT_VISIT.CONSULTING_DATE], \r\n           ");
            viewString.Append(" T.PAT_ADM_CONDITION AS [PAT_VISIT.PAT_ADM_CONDITION], \r\n            T.CONSULTIN");
            viewString.Append("G_DOCTOR AS [PAT_VISIT.CONSULTING_DOCTOR], \r\n            T.ADMITTED_BY AS [PAT_V");
            viewString.Append("ISIT.ADMITTED_BY], \r\n            T.EMER_TREAT_TIMES AS [PAT_VISIT.EMER_TREAT_TIM");
            viewString.Append("ES], \r\n            T.ESC_EMER_TIMES AS [PAT_VISIT.ESC_EMER_TIMES], \r\n           ");
            viewString.Append(" T.SPEC_LEVEL_NURS_DAYS AS [PAT_VISIT.SPEC_LEVEL_NURS_DAYS], \r\n            T.FIR");
            viewString.Append("ST_LEVEL_NURS_DAYS AS [PAT_VISIT.FIRST_LEVEL_NURS_DAYS], \r\n            T.AUTOPSY");
            viewString.Append("_INDICATOR AS [PAT_VISIT.AUTOPSY_INDICATOR], \r\n            T.BLOOD_TYPE AS [PAT_");
            viewString.Append("VISIT.BLOOD_TYPE], \r\n            T.BLOOD_TRAN_TIMES AS [PAT_VISIT.BLOOD_TRAN_TIM");
            viewString.Append("ES], \r\n            T.BLOOD_TRAN_VOL AS [PAT_VISIT.BLOOD_TRAN_VOL], \r\n           ");
            viewString.Append(" T.BLOOD_TRAN_REACT_TIMES AS [PAT_VISIT.BLOOD_TRAN_REACT_TIMES], \r\n            T");
            viewString.Append(".ALERGY_DRUGS AS [PAT_VISIT.ALERGY_DRUGS], \r\n            T.MR_VALUE AS [PAT_VISI");
            viewString.Append("T.MR_VALUE], \r\n            T.MR_QUALITY AS [PAT_VISIT.MR_QUALITY], \r\n           ");
            viewString.Append(" T.FOLLOW_INDICATOR AS [PAT_VISIT.FOLLOW_INDICATOR], \r\n            T.FOLLOW_INTE");
            viewString.Append("RVAL AS [PAT_VISIT.FOLLOW_INTERVAL], \r\n            T.FOLLOW_INTERVAL_UNITS AS [P");
            viewString.Append("AT_VISIT.FOLLOW_INTERVAL_UNITS], \r\n            T.DIRECTOR AS [PAT_VISIT.DIRECTOR");
            viewString.Append("], \r\n            T.ATTENDING_DOCTOR AS [PAT_VISIT.ATTENDING_DOCTOR], \r\n         ");
            viewString.Append("   T.DOCTOR_IN_CHARGE AS [PAT_VISIT.DOCTOR_IN_CHARGE], \r\n            T.DISCHARGE");
            viewString.Append("_DISPOSITION AS [PAT_VISIT.DISCHARGE_DISPOSITION], \r\n            T.TOTAL_COSTS A");
            viewString.Append("S [PAT_VISIT.TOTAL_COSTS], \r\n            T.TOTAL_PAYMENTS AS [PAT_VISIT.TOTAL_PA");
            viewString.Append("YMENTS], \r\n            T.CATALOG_DATE AS [PAT_VISIT.CATALOG_DATE], \r\n           ");
            viewString.Append(" T.CATALOGER AS [PAT_VISIT.CATALOGER], \r\n            T.WORKING_STSTUS AS [PAT_VI");
            viewString.Append("SIT.WORKING_STSTUS], \r\n            T.SERIOUS_COND_DAYS AS [PAT_VISIT.SERIOUS_CON");
            viewString.Append("D_DAYS], \r\n            T.CRITICAL_COND_DAYS AS [PAT_VISIT.CRITICAL_COND_DAYS], \r");
            viewString.Append("\n            T.ICU_DAYS AS [PAT_VISIT.ICU_DAYS], \r\n            T.CCU_DAYS AS [PA");
            viewString.Append("T_VISIT.CCU_DAYS], \r\n            T.SECOND_LEVEL_NURS_DAYS AS [PAT_VISIT.SECOND_L");
            viewString.Append("EVEL_NURS_DAYS], \r\n            T.INFUSION_REACT_TIMES AS [PAT_VISIT.INFUSION_REA");
            viewString.Append("CT_TIMES], \r\n            T.DECUBITAL_ULCER_TIMES AS [PAT_VISIT.DECUBITAL_ULCER_T");
            viewString.Append("IMES], \r\n            T.WORKING_STATUS AS [PAT_VISIT.WORKING_STATUS], \r\n         ");
            viewString.Append("   T.BLOOD_TYPE_RH AS [PAT_VISIT.BLOOD_TYPE_RH], \r\n            T.ADVERSE_REACTIO");
            viewString.Append("N_DRUGS AS [PAT_VISIT.ADVERSE_REACTION_DRUGS], \r\n            T.TOP_UNIT AS [PAT_");
            viewString.Append("VISIT.TOP_UNIT], \r\n            T.SERVICE_SYSTEM_INDICATOR AS [PAT_VISIT.SERVICE_");
            viewString.Append("SYSTEM_INDICATOR], \r\n            T.HEALTH_LEVEL AS [PAT_VISIT.HEALTH_LEVEL], \r\n ");
            viewString.Append("           T.MR_INFECT_REPORT AS [PAT_VISIT.MR_INFECT_REPORT], \r\n            T.I");
            viewString.Append("NFECT_INDICATOR AS [PAT_VISIT.INFECT_INDICATOR], \r\n            T.MR_BACK_DATE_TI");
            viewString.Append("ME AS [PAT_VISIT.MR_BACK_DATE_TIME], \r\n            T.MR_BACK_MAN AS [PAT_VISIT.M");
            viewString.Append("R_BACK_MAN], \r\n            T.BODY_WEIGHT AS [PAT_VISIT.BODY_WEIGHT], \r\n         ");
            viewString.Append("   T.BODY_HEIGHT AS [PAT_VISIT.BODY_HEIGHT], \r\n            T.INTERNAL_NO AS [PAT");
            viewString.Append("_VISIT.INTERNAL_NO], \r\n            T.IDENTITY_CLASS AS [PAT_VISIT.IDENTITY_CLASS");
            viewString.Append("], \r\n            T.HBSAG_INDICATOR AS [PAT_VISIT.HBSAG_INDICATOR], \r\n           ");
            viewString.Append(" T.HCV_AB_INDICATOR AS [PAT_VISIT.HCV_AB_INDICATOR], \r\n            T.HIV_AB_INDI");
            viewString.Append("CATOR AS [PAT_VISIT.HIV_AB_INDICATOR], \r\n            T.CHIEF_DOCTOR AS [PAT_VISI");
            viewString.Append("T.CHIEF_DOCTOR], \r\n            T.ADVANCED_STUDIES_DOCTOR AS [PAT_VISIT.ADVANCED_");
            viewString.Append("STUDIES_DOCTOR], \r\n            T.PRACTICE_DOCTOR_OF_GRADUATE AS [PAT_VISIT.PRACT");
            viewString.Append("ICE_DOCTOR_OF_GRADUATE], \r\n            T.PRACTICE_DOCTOR AS [PAT_VISIT.PRACTICE_");
            viewString.Append("DOCTOR], \r\n            T.DOCTOR_OF_CONTROL_QUALITY AS [PAT_VISIT.DOCTOR_OF_CONTR");
            viewString.Append("OL_QUALITY], \r\n            T.NURSE_OF_CONTROL_QUALITY AS [PAT_VISIT.NURSE_OF_CON");
            viewString.Append("TROL_QUALITY], \r\n            T.DATE_OF_CONTROL_QUALITY AS [PAT_VISIT.DATE_OF_CON");
            viewString.Append("TROL_QUALITY], \r\n            T.FIRST_CASE_INDICATOR AS [PAT_VISIT.FIRST_CASE_IND");
            viewString.Append("ICATOR], \r\n            T.THIRD_LEVEL_NURS_DAYS AS [PAT_VISIT.THIRD_LEVEL_NURS_DA");
            viewString.Append("YS], \r\n            T.X_EXAM_NO AS [PAT_VISIT.X_EXAM_NO], \r\n            T.MEDICAL");
            viewString.Append("_PAY_WAY AS [PAT_VISIT.MEDICAL_PAY_WAY], \r\n            T.FIRST_AID_INDICATOR AS ");
            viewString.Append("[PAT_VISIT.FIRST_AID_INDICATOR], \r\n            T.MTD_VALUE AS [PAT_VISIT.MTD_VAL");
            viewString.Append("UE], \r\n            T.REQUEST_DOCTOR_ID AS [PAT_VISIT.REQUEST_DOCTOR_ID], \r\n     ");
            viewString.Append("       T.PARENT_DOCTOR_ID AS [PAT_VISIT.PARENT_DOCTOR_ID], \r\n            T.SUPER");
            viewString.Append("_DOCTOR_ID AS [PAT_VISIT.SUPER_DOCTOR_ID], \r\n            T.BED_LABEL AS [PAT_VIS");
            viewString.Append("IT.BED_LABEL], \r\n            T.BED_NO AS [PAT_VISIT.BED_NO], \r\n            T.DIA");
            viewString.Append("GNOSIS_DATE AS [PAT_VISIT.DIAGNOSIS_DATE], \r\n            T.MR_SCORE AS [PAT_VISI");
            viewString.Append("T.MR_SCORE], \r\n            T.PAPER_MR_RECEIVE_DATE AS [PAT_VISIT.PAPER_MR_RECEIV");
            viewString.Append("E_DATE], \r\n            T.PAPER_MR_OFFSET_DAYS AS [PAT_VISIT.PAPER_MR_OFFSET_DAYS");
            viewString.Append("], \r\n            T.BED_ADMISSION_TO AS [PAT_VISIT.BED_ADMISSION_TO], \r\n         ");
            viewString.Append("   T.BED_DISCHARGE_FROM AS [PAT_VISIT.BED_DISCHARGE_FROM], \r\n            T.PAPER");
            viewString.Append("_MR_RECEIVE_OPER_DATE AS [PAT_VISIT.PAPER_MR_RECEIVE_OPER_DATE], \r\n            T");
            viewString.Append(".PAPER_MR_RECEIVE_OPERATOR AS [PAT_VISIT.PAPER_MR_RECEIVE_OPERATOR], \r\n         ");
            viewString.Append("   T.PAPER_MR_RECEIVE_NURSE AS [PAT_VISIT.PAPER_MR_RECEIVE_NURSE], \r\n           ");
            viewString.Append(" T.PAPER_MR_RECEIVE_NURSE_DATE AS [PAT_VISIT.PAPER_MR_RECEIVE_NURSE_DATE], \r\n   ");
            viewString.Append("         T.PAPER_MR_RETURNER AS [PAT_VISIT.PAPER_MR_RETURNER], \r\n            T.C");
            viewString.Append("LINIC_TYPE AS [PAT_VISIT.CLINIC_TYPE], \r\n            T.CLINIC_VISIT_NO AS [PAT_V");
            viewString.Append("ISIT.CLINIC_VISIT_NO], \r\n            T.CLINIC_REGISTRY_STATUS AS [PAT_VISIT.CLIN");
            viewString.Append("IC_REGISTRY_STATUS], \r\n            T.CLINIC_DOCTOR_ID AS [PAT_VISIT.CLINIC_DOCTO");
            viewString.Append("R_ID], \r\n            T.GH_DATE AS [PAT_VISIT.GH_DATE], \r\n            T.GH_DEPT_C");
            viewString.Append("ODE AS [PAT_VISIT.GH_DEPT_CODE], \r\n            T.GH_OPERATOR AS [PAT_VISIT.GH_OP");
            viewString.Append("ERATOR], \r\n            T.THREE_DAY_DIAGNOSIS_CODE AS [PAT_VISIT.THREE_DAY_DIAGNO");
            viewString.Append("SIS_CODE], \r\n            T.THREE_DAY_DIAGNOSIS_NAME AS [PAT_VISIT.THREE_DAY_DIAG");
            viewString.Append("NOSIS_NAME], \r\n            T.THREE_DAY_DIAGNOSIS_REASON AS [PAT_VISIT.THREE_DAY_");
            viewString.Append("DIAGNOSIS_REASON], \r\n            T.MR_DOCTOR_PART_STATUS AS [PAT_VISIT.MR_DOCTOR");
            viewString.Append("_PART_STATUS], \r\n            T.MR_NURSE_PART_STATUS AS [PAT_VISIT.MR_NURSE_PART_");
            viewString.Append("STATUS], \r\n            T.IN_CONSULT_TIMES AS [PAT_VISIT.IN_CONSULT_TIMES], \r\n   ");
            viewString.Append("         T.FAR_CONSULT_TIMES AS [PAT_VISIT.FAR_CONSULT_TIMES], \r\n            T.B");
            viewString.Append("ABY_FLAG AS [PAT_VISIT.BABY_FLAG], \r\n            T.WARD_ADMISSION_TO AS [PAT_VIS");
            viewString.Append("IT.WARD_ADMISSION_TO], \r\n            T.WARD_DISCHARGE_FROM AS [PAT_VISIT.WARD_DI");
            viewString.Append("SCHARGE_FROM], \r\n            T.INP_NO AS [PAT_VISIT.INP_NO], \r\n            T.MR_");
            viewString.Append("NURSE_SCORE AS [PAT_VISIT.MR_NURSE_SCORE], \r\n            T.MR_DOCTOR_SCORE AS [P");
            viewString.Append("AT_VISIT.MR_DOCTOR_SCORE], \r\n            T.WARD_DATE_TIME AS [PAT_VISIT.WARD_DAT");
            viewString.Append("E_TIME], \r\n            T.PAPER_MR_RECEIVER AS [PAT_VISIT.PAPER_MR_RECEIVER], \r\n ");
            viewString.Append("           T.FOLLOW_OVER_DATE_TIME AS [PAT_VISIT.FOLLOW_OVER_DATE_TIME], \r\n     ");
            viewString.Append("       T.MRQC_DOCT_ID AS [PAT_VISIT.MRQC_DOCT_ID], \r\n            T.MRQC_DOCT_DAT");
            viewString.Append("E_TIME AS [PAT_VISIT.MRQC_DOCT_DATE_TIME], \r\n            T.DIRECTOR_ID AS [PAT_V");
            viewString.Append("ISIT.DIRECTOR_ID], \r\n            T.CHIEF_DOCTOR_ID AS [PAT_VISIT.CHIEF_DOCTOR_ID");
            viewString.Append("], \r\n            T.ATTENDING_DOCTOR_ID AS [PAT_VISIT.ATTENDING_DOCTOR_ID], \r\n   ");
            viewString.Append("         T.DOCTOR_IN_CHARGE_ID AS [PAT_VISIT.DOCTOR_IN_CHARGE_ID], \r\n           ");
            viewString.Append(" T.ADVANCED_STUDIES_DOCTOR_ID AS [PAT_VISIT.ADVANCED_STUDIES_DOCTOR_ID], \r\n     ");
            viewString.Append("       T.PRACTICE_DOCTOR_ID AS [PAT_VISIT.PRACTICE_DOCTOR_ID], \r\n            T.P");
            viewString.Append("RACTICE_DOCTOR_OF_GRADUATE_ID AS [PAT_VISIT.PRACTICE_DOCTOR_OF_GRADUATE_ID], \r\n ");
            viewString.Append("           T.DEATH_DATE_TIME AS [PAT_VISIT.DEATH_DATE_TIME], \r\n            T.IN_");
            viewString.Append("CP_DATE AS [PAT_VISIT.IN_CP_DATE], \r\n            T.IN_CP_USER_ID AS [PAT_VISIT.I");
            viewString.Append("N_CP_USER_ID], \r\n            T.CP_STATUS AS [PAT_VISIT.CP_STATUS], \r\n           ");
            viewString.Append(" T.CP_ID AS [PAT_VISIT.CP_ID], \r\n            T.OUT_CP_DATE AS [PAT_VISIT.OUT_CP_");
            viewString.Append("DATE], \r\n            T.IN_CP_DAYS AS [PAT_VISIT.IN_CP_DAYS], \r\n            T.THR");
            viewString.Append("EE_DAY_OPERATION AS [PAT_VISIT.THREE_DAY_OPERATION], \r\n            T.ALERGY_DRUG");
            viewString.Append("S1 AS [PAT_VISIT.ALERGY_DRUGS1], \r\n            T.INP_NO_ALIAS AS [PAT_VISIT.INP_");
            viewString.Append("NO_ALIAS], \r\n            T.CP_MEMO AS [PAT_VISIT.CP_MEMO], \r\n            T.CP_EX");
            viewString.Append("CLUDE_ID AS [PAT_VISIT.CP_EXCLUDE_ID], \r\n            T.CP_EXCLUDE_NAME AS [PAT_V");
            viewString.Append("ISIT.CP_EXCLUDE_NAME], \r\n            T.CLINICAL_PATHWAY AS [PAT_VISIT.CLINICAL_P");
            viewString.Append("ATHWAY], \r\n            T.PAT_ORIGIN AS [PAT_VISIT.PAT_ORIGIN], \r\n            T.X");
            viewString.Append("_CT_NO AS [PAT_VISIT.X_CT_NO], \r\n            T.X_MRI_NO AS [PAT_VISIT.X_MRI_NO],");
            viewString.Append(" \r\n            T.X_TUMOUR_CARD AS [PAT_VISIT.X_TUMOUR_CARD], \r\n            T.X_C");
            viewString.Append("ONTAGION_CARD AS [PAT_VISIT.X_CONTAGION_CARD], \r\n            T.BA_VISIT_ID AS [P");
            viewString.Append("AT_VISIT.BA_VISIT_ID], \r\n            T.PHONE_MAILING_ADDRESS AS [PAT_VISIT.PHONE");
            viewString.Append("_MAILING_ADDRESS], \r\n            T.X_Xshexian_NO AS [PAT_VISIT.X_Xshexian_NO], \r");
            viewString.Append("\n            T.dept_transfer AS [PAT_VISIT.dept_transfer], \r\n            T.Shuxu");
            viewString.Append("ePinzhong AS [PAT_VISIT.ShuxuePinzhong], \r\n            T.PAT_AGE AS [PAT_VISIT.P");
            viewString.Append("AT_AGE], \r\n            T.PAT_BIRTHDAY_BABY AS [PAT_VISIT.PAT_BIRTHDAY_BABY], \r\n ");
            viewString.Append("           T.NURSE_GROUP_NO AS [PAT_VISIT.NURSE_GROUP_NO], \r\n            T.myID ");
            viewString.Append("AS [PAT_VISIT.myID], \r\n            True AS _from0\r\n        FROM EF_EMREntities.P");
            viewString.Append("AT_VISIT AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("EF_EMRModelStoreContainer.PAT_VISIT", viewString.ToString());
        }
        
        /// <Summary>
        /// 返回 EF_EMREntities.PAT_VISIT 的视图
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(16191);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PAT_VISIT\r\n        [EF_EMRModel.PAT_VISIT](T1");
            viewString.Append(".[PAT_VISIT.PATIENT_ID], T1.[PAT_VISIT.VISIT_ID], T1.[PAT_VISIT.DEPT_ADMISSION_T");
            viewString.Append("O], T1.[PAT_VISIT.ADMISSION_DATE_TIME], T1.[PAT_VISIT.DEPT_DISCHARGE_FROM], T1.[");
            viewString.Append("PAT_VISIT.DISCHARGE_DATE_TIME], T1.[PAT_VISIT.OCCUPATION], T1.[PAT_VISIT.MARITAL");
            viewString.Append("_STATUS], T1.[PAT_VISIT.IDENTITY], T1.[PAT_VISIT.ARMED_SERVICES], T1.[PAT_VISIT.");
            viewString.Append("DUTY], T1.[PAT_VISIT.UNIT_IN_CONTRACT], T1.[PAT_VISIT.CHARGE_TYPE], T1.[PAT_VISI");
            viewString.Append("T.INSURANCE_TYPE], T1.[PAT_VISIT.INSURANCE_NO], T1.[PAT_VISIT.SERVICE_AGENCY], T");
            viewString.Append("1.[PAT_VISIT.MAILING_ADDRESS], T1.[PAT_VISIT.ZIP_CODE], T1.[PAT_VISIT.NEXT_OF_KI");
            viewString.Append("N], T1.[PAT_VISIT.RELATIONSHIP], T1.[PAT_VISIT.NEXT_OF_KIN_ADDR], T1.[PAT_VISIT.");
            viewString.Append("NEXT_OF_KIN_ZIPCODE], T1.[PAT_VISIT.NEXT_OF_KIN_PHONE], T1.[PAT_VISIT.PATIENT_CL");
            viewString.Append("ASS], T1.[PAT_VISIT.ADMISSION_CAUSE], T1.[PAT_VISIT.CONSULTING_DATE], T1.[PAT_VI");
            viewString.Append("SIT.PAT_ADM_CONDITION], T1.[PAT_VISIT.CONSULTING_DOCTOR], T1.[PAT_VISIT.ADMITTED");
            viewString.Append("_BY], T1.[PAT_VISIT.EMER_TREAT_TIMES], T1.[PAT_VISIT.ESC_EMER_TIMES], T1.[PAT_VI");
            viewString.Append("SIT.SPEC_LEVEL_NURS_DAYS], T1.[PAT_VISIT.FIRST_LEVEL_NURS_DAYS], T1.[PAT_VISIT.A");
            viewString.Append("UTOPSY_INDICATOR], T1.[PAT_VISIT.BLOOD_TYPE], T1.[PAT_VISIT.BLOOD_TRAN_TIMES], T");
            viewString.Append("1.[PAT_VISIT.BLOOD_TRAN_VOL], T1.[PAT_VISIT.BLOOD_TRAN_REACT_TIMES], T1.[PAT_VIS");
            viewString.Append("IT.ALERGY_DRUGS], T1.[PAT_VISIT.MR_VALUE], T1.[PAT_VISIT.MR_QUALITY], T1.[PAT_VI");
            viewString.Append("SIT.FOLLOW_INDICATOR], T1.[PAT_VISIT.FOLLOW_INTERVAL], T1.[PAT_VISIT.FOLLOW_INTE");
            viewString.Append("RVAL_UNITS], T1.[PAT_VISIT.DIRECTOR], T1.[PAT_VISIT.ATTENDING_DOCTOR], T1.[PAT_V");
            viewString.Append("ISIT.DOCTOR_IN_CHARGE], T1.[PAT_VISIT.DISCHARGE_DISPOSITION], T1.[PAT_VISIT.TOTA");
            viewString.Append("L_COSTS], T1.[PAT_VISIT.TOTAL_PAYMENTS], T1.[PAT_VISIT.CATALOG_DATE], T1.[PAT_VI");
            viewString.Append("SIT.CATALOGER], T1.[PAT_VISIT.WORKING_STSTUS], T1.[PAT_VISIT.SERIOUS_COND_DAYS],");
            viewString.Append(" T1.[PAT_VISIT.CRITICAL_COND_DAYS], T1.[PAT_VISIT.ICU_DAYS], T1.[PAT_VISIT.CCU_D");
            viewString.Append("AYS], T1.[PAT_VISIT.SECOND_LEVEL_NURS_DAYS], T1.[PAT_VISIT.INFUSION_REACT_TIMES]");
            viewString.Append(", T1.[PAT_VISIT.DECUBITAL_ULCER_TIMES], T1.[PAT_VISIT.WORKING_STATUS], T1.[PAT_V");
            viewString.Append("ISIT.BLOOD_TYPE_RH], T1.[PAT_VISIT.ADVERSE_REACTION_DRUGS], T1.[PAT_VISIT.TOP_UN");
            viewString.Append("IT], T1.[PAT_VISIT.SERVICE_SYSTEM_INDICATOR], T1.[PAT_VISIT.HEALTH_LEVEL], T1.[P");
            viewString.Append("AT_VISIT.MR_INFECT_REPORT], T1.[PAT_VISIT.INFECT_INDICATOR], T1.[PAT_VISIT.MR_BA");
            viewString.Append("CK_DATE_TIME], T1.[PAT_VISIT.MR_BACK_MAN], T1.[PAT_VISIT.BODY_WEIGHT], T1.[PAT_V");
            viewString.Append("ISIT.BODY_HEIGHT], T1.[PAT_VISIT.INTERNAL_NO], T1.[PAT_VISIT.IDENTITY_CLASS], T1");
            viewString.Append(".[PAT_VISIT.HBSAG_INDICATOR], T1.[PAT_VISIT.HCV_AB_INDICATOR], T1.[PAT_VISIT.HIV");
            viewString.Append("_AB_INDICATOR], T1.[PAT_VISIT.CHIEF_DOCTOR], T1.[PAT_VISIT.ADVANCED_STUDIES_DOCT");
            viewString.Append("OR], T1.[PAT_VISIT.PRACTICE_DOCTOR_OF_GRADUATE], T1.[PAT_VISIT.PRACTICE_DOCTOR],");
            viewString.Append(" T1.[PAT_VISIT.DOCTOR_OF_CONTROL_QUALITY], T1.[PAT_VISIT.NURSE_OF_CONTROL_QUALIT");
            viewString.Append("Y], T1.[PAT_VISIT.DATE_OF_CONTROL_QUALITY], T1.[PAT_VISIT.FIRST_CASE_INDICATOR],");
            viewString.Append(" T1.[PAT_VISIT.THIRD_LEVEL_NURS_DAYS], T1.[PAT_VISIT.X_EXAM_NO], T1.[PAT_VISIT.M");
            viewString.Append("EDICAL_PAY_WAY], T1.[PAT_VISIT.FIRST_AID_INDICATOR], T1.[PAT_VISIT.MTD_VALUE], T");
            viewString.Append("1.[PAT_VISIT.REQUEST_DOCTOR_ID], T1.[PAT_VISIT.PARENT_DOCTOR_ID], T1.[PAT_VISIT.");
            viewString.Append("SUPER_DOCTOR_ID], T1.[PAT_VISIT.BED_LABEL], T1.[PAT_VISIT.BED_NO], T1.[PAT_VISIT");
            viewString.Append(".DIAGNOSIS_DATE], T1.[PAT_VISIT.MR_SCORE], T1.[PAT_VISIT.PAPER_MR_RECEIVE_DATE],");
            viewString.Append(" T1.[PAT_VISIT.PAPER_MR_OFFSET_DAYS], T1.[PAT_VISIT.BED_ADMISSION_TO], T1.[PAT_V");
            viewString.Append("ISIT.BED_DISCHARGE_FROM], T1.[PAT_VISIT.PAPER_MR_RECEIVE_OPER_DATE], T1.[PAT_VIS");
            viewString.Append("IT.PAPER_MR_RECEIVE_OPERATOR], T1.[PAT_VISIT.PAPER_MR_RECEIVE_NURSE], T1.[PAT_VI");
            viewString.Append("SIT.PAPER_MR_RECEIVE_NURSE_DATE], T1.[PAT_VISIT.PAPER_MR_RETURNER], T1.[PAT_VISI");
            viewString.Append("T.CLINIC_TYPE], T1.[PAT_VISIT.CLINIC_VISIT_NO], T1.[PAT_VISIT.CLINIC_REGISTRY_ST");
            viewString.Append("ATUS], T1.[PAT_VISIT.CLINIC_DOCTOR_ID], T1.[PAT_VISIT.GH_DATE], T1.[PAT_VISIT.GH");
            viewString.Append("_DEPT_CODE], T1.[PAT_VISIT.GH_OPERATOR], T1.[PAT_VISIT.THREE_DAY_DIAGNOSIS_CODE]");
            viewString.Append(", T1.[PAT_VISIT.THREE_DAY_DIAGNOSIS_NAME], T1.[PAT_VISIT.THREE_DAY_DIAGNOSIS_REA");
            viewString.Append("SON], T1.[PAT_VISIT.MR_DOCTOR_PART_STATUS], T1.[PAT_VISIT.MR_NURSE_PART_STATUS],");
            viewString.Append(" T1.[PAT_VISIT.IN_CONSULT_TIMES], T1.[PAT_VISIT.FAR_CONSULT_TIMES], T1.[PAT_VISI");
            viewString.Append("T.BABY_FLAG], T1.[PAT_VISIT.WARD_ADMISSION_TO], T1.[PAT_VISIT.WARD_DISCHARGE_FRO");
            viewString.Append("M], T1.[PAT_VISIT.INP_NO], T1.[PAT_VISIT.MR_NURSE_SCORE], T1.[PAT_VISIT.MR_DOCTO");
            viewString.Append("R_SCORE], T1.[PAT_VISIT.WARD_DATE_TIME], T1.[PAT_VISIT.PAPER_MR_RECEIVER], T1.[P");
            viewString.Append("AT_VISIT.FOLLOW_OVER_DATE_TIME], T1.[PAT_VISIT.MRQC_DOCT_ID], T1.[PAT_VISIT.MRQC");
            viewString.Append("_DOCT_DATE_TIME], T1.[PAT_VISIT.DIRECTOR_ID], T1.[PAT_VISIT.CHIEF_DOCTOR_ID], T1");
            viewString.Append(".[PAT_VISIT.ATTENDING_DOCTOR_ID], T1.[PAT_VISIT.DOCTOR_IN_CHARGE_ID], T1.[PAT_VI");
            viewString.Append("SIT.ADVANCED_STUDIES_DOCTOR_ID], T1.[PAT_VISIT.PRACTICE_DOCTOR_ID], T1.[PAT_VISI");
            viewString.Append("T.PRACTICE_DOCTOR_OF_GRADUATE_ID], T1.[PAT_VISIT.DEATH_DATE_TIME], T1.[PAT_VISIT");
            viewString.Append(".IN_CP_DATE], T1.[PAT_VISIT.IN_CP_USER_ID], T1.[PAT_VISIT.CP_STATUS], T1.[PAT_VI");
            viewString.Append("SIT.CP_ID], T1.[PAT_VISIT.OUT_CP_DATE], T1.[PAT_VISIT.IN_CP_DAYS], T1.[PAT_VISIT");
            viewString.Append(".THREE_DAY_OPERATION], T1.[PAT_VISIT.ALERGY_DRUGS1], T1.[PAT_VISIT.INP_NO_ALIAS]");
            viewString.Append(", T1.[PAT_VISIT.CP_MEMO], T1.[PAT_VISIT.CP_EXCLUDE_ID], T1.[PAT_VISIT.CP_EXCLUDE");
            viewString.Append("_NAME], T1.[PAT_VISIT.CLINICAL_PATHWAY], T1.[PAT_VISIT.PAT_ORIGIN], T1.[PAT_VISI");
            viewString.Append("T.X_CT_NO], T1.[PAT_VISIT.X_MRI_NO], T1.[PAT_VISIT.X_TUMOUR_CARD], T1.[PAT_VISIT");
            viewString.Append(".X_CONTAGION_CARD], T1.[PAT_VISIT.BA_VISIT_ID], T1.[PAT_VISIT.PHONE_MAILING_ADDR");
            viewString.Append("ESS], T1.[PAT_VISIT.X_Xshexian_NO], T1.[PAT_VISIT.dept_transfer], T1.[PAT_VISIT.");
            viewString.Append("ShuxuePinzhong], T1.[PAT_VISIT.PAT_AGE], T1.[PAT_VISIT.PAT_BIRTHDAY_BABY], T1.[P");
            viewString.Append("AT_VISIT.NURSE_GROUP_NO], T1.[PAT_VISIT.myID])\r\n    FROM (\r\n        SELECT \r\n   ");
            viewString.Append("         T.PATIENT_ID AS [PAT_VISIT.PATIENT_ID], \r\n            T.VISIT_ID AS [PA");
            viewString.Append("T_VISIT.VISIT_ID], \r\n            T.DEPT_ADMISSION_TO AS [PAT_VISIT.DEPT_ADMISSIO");
            viewString.Append("N_TO], \r\n            T.ADMISSION_DATE_TIME AS [PAT_VISIT.ADMISSION_DATE_TIME], \r");
            viewString.Append("\n            T.DEPT_DISCHARGE_FROM AS [PAT_VISIT.DEPT_DISCHARGE_FROM], \r\n       ");
            viewString.Append("     T.DISCHARGE_DATE_TIME AS [PAT_VISIT.DISCHARGE_DATE_TIME], \r\n            T.O");
            viewString.Append("CCUPATION AS [PAT_VISIT.OCCUPATION], \r\n            T.MARITAL_STATUS AS [PAT_VISI");
            viewString.Append("T.MARITAL_STATUS], \r\n            T.IDENTITY AS [PAT_VISIT.IDENTITY], \r\n         ");
            viewString.Append("   T.ARMED_SERVICES AS [PAT_VISIT.ARMED_SERVICES], \r\n            T.DUTY AS [PAT_");
            viewString.Append("VISIT.DUTY], \r\n            T.UNIT_IN_CONTRACT AS [PAT_VISIT.UNIT_IN_CONTRACT], \r");
            viewString.Append("\n            T.CHARGE_TYPE AS [PAT_VISIT.CHARGE_TYPE], \r\n            T.INSURANCE");
            viewString.Append("_TYPE AS [PAT_VISIT.INSURANCE_TYPE], \r\n            T.INSURANCE_NO AS [PAT_VISIT.");
            viewString.Append("INSURANCE_NO], \r\n            T.SERVICE_AGENCY AS [PAT_VISIT.SERVICE_AGENCY], \r\n ");
            viewString.Append("           T.MAILING_ADDRESS AS [PAT_VISIT.MAILING_ADDRESS], \r\n            T.ZIP");
            viewString.Append("_CODE AS [PAT_VISIT.ZIP_CODE], \r\n            T.NEXT_OF_KIN AS [PAT_VISIT.NEXT_OF");
            viewString.Append("_KIN], \r\n            T.[RELATIONSHIP] AS [PAT_VISIT.RELATIONSHIP], \r\n           ");
            viewString.Append(" T.NEXT_OF_KIN_ADDR AS [PAT_VISIT.NEXT_OF_KIN_ADDR], \r\n            T.NEXT_OF_KIN");
            viewString.Append("_ZIPCODE AS [PAT_VISIT.NEXT_OF_KIN_ZIPCODE], \r\n            T.NEXT_OF_KIN_PHONE A");
            viewString.Append("S [PAT_VISIT.NEXT_OF_KIN_PHONE], \r\n            T.PATIENT_CLASS AS [PAT_VISIT.PAT");
            viewString.Append("IENT_CLASS], \r\n            T.ADMISSION_CAUSE AS [PAT_VISIT.ADMISSION_CAUSE], \r\n ");
            viewString.Append("           T.CONSULTING_DATE AS [PAT_VISIT.CONSULTING_DATE], \r\n            T.PAT");
            viewString.Append("_ADM_CONDITION AS [PAT_VISIT.PAT_ADM_CONDITION], \r\n            T.CONSULTING_DOCT");
            viewString.Append("OR AS [PAT_VISIT.CONSULTING_DOCTOR], \r\n            T.ADMITTED_BY AS [PAT_VISIT.A");
            viewString.Append("DMITTED_BY], \r\n            T.EMER_TREAT_TIMES AS [PAT_VISIT.EMER_TREAT_TIMES], \r");
            viewString.Append("\n            T.ESC_EMER_TIMES AS [PAT_VISIT.ESC_EMER_TIMES], \r\n            T.SPE");
            viewString.Append("C_LEVEL_NURS_DAYS AS [PAT_VISIT.SPEC_LEVEL_NURS_DAYS], \r\n            T.FIRST_LEV");
            viewString.Append("EL_NURS_DAYS AS [PAT_VISIT.FIRST_LEVEL_NURS_DAYS], \r\n            T.AUTOPSY_INDIC");
            viewString.Append("ATOR AS [PAT_VISIT.AUTOPSY_INDICATOR], \r\n            T.BLOOD_TYPE AS [PAT_VISIT.");
            viewString.Append("BLOOD_TYPE], \r\n            T.BLOOD_TRAN_TIMES AS [PAT_VISIT.BLOOD_TRAN_TIMES], \r");
            viewString.Append("\n            T.BLOOD_TRAN_VOL AS [PAT_VISIT.BLOOD_TRAN_VOL], \r\n            T.BLO");
            viewString.Append("OD_TRAN_REACT_TIMES AS [PAT_VISIT.BLOOD_TRAN_REACT_TIMES], \r\n            T.ALERG");
            viewString.Append("Y_DRUGS AS [PAT_VISIT.ALERGY_DRUGS], \r\n            T.MR_VALUE AS [PAT_VISIT.MR_V");
            viewString.Append("ALUE], \r\n            T.MR_QUALITY AS [PAT_VISIT.MR_QUALITY], \r\n            T.FOL");
            viewString.Append("LOW_INDICATOR AS [PAT_VISIT.FOLLOW_INDICATOR], \r\n            T.FOLLOW_INTERVAL A");
            viewString.Append("S [PAT_VISIT.FOLLOW_INTERVAL], \r\n            T.FOLLOW_INTERVAL_UNITS AS [PAT_VIS");
            viewString.Append("IT.FOLLOW_INTERVAL_UNITS], \r\n            T.DIRECTOR AS [PAT_VISIT.DIRECTOR], \r\n ");
            viewString.Append("           T.ATTENDING_DOCTOR AS [PAT_VISIT.ATTENDING_DOCTOR], \r\n            T.D");
            viewString.Append("OCTOR_IN_CHARGE AS [PAT_VISIT.DOCTOR_IN_CHARGE], \r\n            T.DISCHARGE_DISPO");
            viewString.Append("SITION AS [PAT_VISIT.DISCHARGE_DISPOSITION], \r\n            T.TOTAL_COSTS AS [PAT");
            viewString.Append("_VISIT.TOTAL_COSTS], \r\n            T.TOTAL_PAYMENTS AS [PAT_VISIT.TOTAL_PAYMENTS");
            viewString.Append("], \r\n            T.CATALOG_DATE AS [PAT_VISIT.CATALOG_DATE], \r\n            T.CAT");
            viewString.Append("ALOGER AS [PAT_VISIT.CATALOGER], \r\n            T.WORKING_STSTUS AS [PAT_VISIT.WO");
            viewString.Append("RKING_STSTUS], \r\n            T.SERIOUS_COND_DAYS AS [PAT_VISIT.SERIOUS_COND_DAYS");
            viewString.Append("], \r\n            T.CRITICAL_COND_DAYS AS [PAT_VISIT.CRITICAL_COND_DAYS], \r\n     ");
            viewString.Append("       T.ICU_DAYS AS [PAT_VISIT.ICU_DAYS], \r\n            T.CCU_DAYS AS [PAT_VISI");
            viewString.Append("T.CCU_DAYS], \r\n            T.SECOND_LEVEL_NURS_DAYS AS [PAT_VISIT.SECOND_LEVEL_N");
            viewString.Append("URS_DAYS], \r\n            T.INFUSION_REACT_TIMES AS [PAT_VISIT.INFUSION_REACT_TIM");
            viewString.Append("ES], \r\n            T.DECUBITAL_ULCER_TIMES AS [PAT_VISIT.DECUBITAL_ULCER_TIMES],");
            viewString.Append(" \r\n            T.WORKING_STATUS AS [PAT_VISIT.WORKING_STATUS], \r\n            T.B");
            viewString.Append("LOOD_TYPE_RH AS [PAT_VISIT.BLOOD_TYPE_RH], \r\n            T.ADVERSE_REACTION_DRUG");
            viewString.Append("S AS [PAT_VISIT.ADVERSE_REACTION_DRUGS], \r\n            T.TOP_UNIT AS [PAT_VISIT.");
            viewString.Append("TOP_UNIT], \r\n            T.SERVICE_SYSTEM_INDICATOR AS [PAT_VISIT.SERVICE_SYSTEM");
            viewString.Append("_INDICATOR], \r\n            T.HEALTH_LEVEL AS [PAT_VISIT.HEALTH_LEVEL], \r\n       ");
            viewString.Append("     T.MR_INFECT_REPORT AS [PAT_VISIT.MR_INFECT_REPORT], \r\n            T.INFECT_");
            viewString.Append("INDICATOR AS [PAT_VISIT.INFECT_INDICATOR], \r\n            T.MR_BACK_DATE_TIME AS ");
            viewString.Append("[PAT_VISIT.MR_BACK_DATE_TIME], \r\n            T.MR_BACK_MAN AS [PAT_VISIT.MR_BACK");
            viewString.Append("_MAN], \r\n            T.BODY_WEIGHT AS [PAT_VISIT.BODY_WEIGHT], \r\n            T.B");
            viewString.Append("ODY_HEIGHT AS [PAT_VISIT.BODY_HEIGHT], \r\n            T.INTERNAL_NO AS [PAT_VISIT");
            viewString.Append(".INTERNAL_NO], \r\n            T.IDENTITY_CLASS AS [PAT_VISIT.IDENTITY_CLASS], \r\n ");
            viewString.Append("           T.HBSAG_INDICATOR AS [PAT_VISIT.HBSAG_INDICATOR], \r\n            T.HCV");
            viewString.Append("_AB_INDICATOR AS [PAT_VISIT.HCV_AB_INDICATOR], \r\n            T.HIV_AB_INDICATOR ");
            viewString.Append("AS [PAT_VISIT.HIV_AB_INDICATOR], \r\n            T.CHIEF_DOCTOR AS [PAT_VISIT.CHIE");
            viewString.Append("F_DOCTOR], \r\n            T.ADVANCED_STUDIES_DOCTOR AS [PAT_VISIT.ADVANCED_STUDIE");
            viewString.Append("S_DOCTOR], \r\n            T.PRACTICE_DOCTOR_OF_GRADUATE AS [PAT_VISIT.PRACTICE_DO");
            viewString.Append("CTOR_OF_GRADUATE], \r\n            T.PRACTICE_DOCTOR AS [PAT_VISIT.PRACTICE_DOCTOR");
            viewString.Append("], \r\n            T.DOCTOR_OF_CONTROL_QUALITY AS [PAT_VISIT.DOCTOR_OF_CONTROL_QUA");
            viewString.Append("LITY], \r\n            T.NURSE_OF_CONTROL_QUALITY AS [PAT_VISIT.NURSE_OF_CONTROL_Q");
            viewString.Append("UALITY], \r\n            T.DATE_OF_CONTROL_QUALITY AS [PAT_VISIT.DATE_OF_CONTROL_Q");
            viewString.Append("UALITY], \r\n            T.FIRST_CASE_INDICATOR AS [PAT_VISIT.FIRST_CASE_INDICATOR");
            viewString.Append("], \r\n            T.THIRD_LEVEL_NURS_DAYS AS [PAT_VISIT.THIRD_LEVEL_NURS_DAYS], \r");
            viewString.Append("\n            T.X_EXAM_NO AS [PAT_VISIT.X_EXAM_NO], \r\n            T.MEDICAL_PAY_W");
            viewString.Append("AY AS [PAT_VISIT.MEDICAL_PAY_WAY], \r\n            T.FIRST_AID_INDICATOR AS [PAT_V");
            viewString.Append("ISIT.FIRST_AID_INDICATOR], \r\n            T.MTD_VALUE AS [PAT_VISIT.MTD_VALUE], \r");
            viewString.Append("\n            T.REQUEST_DOCTOR_ID AS [PAT_VISIT.REQUEST_DOCTOR_ID], \r\n           ");
            viewString.Append(" T.PARENT_DOCTOR_ID AS [PAT_VISIT.PARENT_DOCTOR_ID], \r\n            T.SUPER_DOCTO");
            viewString.Append("R_ID AS [PAT_VISIT.SUPER_DOCTOR_ID], \r\n            T.BED_LABEL AS [PAT_VISIT.BED");
            viewString.Append("_LABEL], \r\n            T.BED_NO AS [PAT_VISIT.BED_NO], \r\n            T.DIAGNOSIS");
            viewString.Append("_DATE AS [PAT_VISIT.DIAGNOSIS_DATE], \r\n            T.MR_SCORE AS [PAT_VISIT.MR_S");
            viewString.Append("CORE], \r\n            T.PAPER_MR_RECEIVE_DATE AS [PAT_VISIT.PAPER_MR_RECEIVE_DATE");
            viewString.Append("], \r\n            T.PAPER_MR_OFFSET_DAYS AS [PAT_VISIT.PAPER_MR_OFFSET_DAYS], \r\n ");
            viewString.Append("           T.BED_ADMISSION_TO AS [PAT_VISIT.BED_ADMISSION_TO], \r\n            T.B");
            viewString.Append("ED_DISCHARGE_FROM AS [PAT_VISIT.BED_DISCHARGE_FROM], \r\n            T.PAPER_MR_RE");
            viewString.Append("CEIVE_OPER_DATE AS [PAT_VISIT.PAPER_MR_RECEIVE_OPER_DATE], \r\n            T.PAPER");
            viewString.Append("_MR_RECEIVE_OPERATOR AS [PAT_VISIT.PAPER_MR_RECEIVE_OPERATOR], \r\n            T.P");
            viewString.Append("APER_MR_RECEIVE_NURSE AS [PAT_VISIT.PAPER_MR_RECEIVE_NURSE], \r\n            T.PAP");
            viewString.Append("ER_MR_RECEIVE_NURSE_DATE AS [PAT_VISIT.PAPER_MR_RECEIVE_NURSE_DATE], \r\n         ");
            viewString.Append("   T.PAPER_MR_RETURNER AS [PAT_VISIT.PAPER_MR_RETURNER], \r\n            T.CLINIC_");
            viewString.Append("TYPE AS [PAT_VISIT.CLINIC_TYPE], \r\n            T.CLINIC_VISIT_NO AS [PAT_VISIT.C");
            viewString.Append("LINIC_VISIT_NO], \r\n            T.CLINIC_REGISTRY_STATUS AS [PAT_VISIT.CLINIC_REG");
            viewString.Append("ISTRY_STATUS], \r\n            T.CLINIC_DOCTOR_ID AS [PAT_VISIT.CLINIC_DOCTOR_ID],");
            viewString.Append(" \r\n            T.GH_DATE AS [PAT_VISIT.GH_DATE], \r\n            T.GH_DEPT_CODE AS");
            viewString.Append(" [PAT_VISIT.GH_DEPT_CODE], \r\n            T.GH_OPERATOR AS [PAT_VISIT.GH_OPERATOR");
            viewString.Append("], \r\n            T.THREE_DAY_DIAGNOSIS_CODE AS [PAT_VISIT.THREE_DAY_DIAGNOSIS_CO");
            viewString.Append("DE], \r\n            T.THREE_DAY_DIAGNOSIS_NAME AS [PAT_VISIT.THREE_DAY_DIAGNOSIS_");
            viewString.Append("NAME], \r\n            T.THREE_DAY_DIAGNOSIS_REASON AS [PAT_VISIT.THREE_DAY_DIAGNO");
            viewString.Append("SIS_REASON], \r\n            T.MR_DOCTOR_PART_STATUS AS [PAT_VISIT.MR_DOCTOR_PART_");
            viewString.Append("STATUS], \r\n            T.MR_NURSE_PART_STATUS AS [PAT_VISIT.MR_NURSE_PART_STATUS");
            viewString.Append("], \r\n            T.IN_CONSULT_TIMES AS [PAT_VISIT.IN_CONSULT_TIMES], \r\n         ");
            viewString.Append("   T.FAR_CONSULT_TIMES AS [PAT_VISIT.FAR_CONSULT_TIMES], \r\n            T.BABY_FL");
            viewString.Append("AG AS [PAT_VISIT.BABY_FLAG], \r\n            T.WARD_ADMISSION_TO AS [PAT_VISIT.WAR");
            viewString.Append("D_ADMISSION_TO], \r\n            T.WARD_DISCHARGE_FROM AS [PAT_VISIT.WARD_DISCHARG");
            viewString.Append("E_FROM], \r\n            T.INP_NO AS [PAT_VISIT.INP_NO], \r\n            T.MR_NURSE_");
            viewString.Append("SCORE AS [PAT_VISIT.MR_NURSE_SCORE], \r\n            T.MR_DOCTOR_SCORE AS [PAT_VIS");
            viewString.Append("IT.MR_DOCTOR_SCORE], \r\n            T.WARD_DATE_TIME AS [PAT_VISIT.WARD_DATE_TIME");
            viewString.Append("], \r\n            T.PAPER_MR_RECEIVER AS [PAT_VISIT.PAPER_MR_RECEIVER], \r\n       ");
            viewString.Append("     T.FOLLOW_OVER_DATE_TIME AS [PAT_VISIT.FOLLOW_OVER_DATE_TIME], \r\n           ");
            viewString.Append(" T.MRQC_DOCT_ID AS [PAT_VISIT.MRQC_DOCT_ID], \r\n            T.MRQC_DOCT_DATE_TIME");
            viewString.Append(" AS [PAT_VISIT.MRQC_DOCT_DATE_TIME], \r\n            T.DIRECTOR_ID AS [PAT_VISIT.D");
            viewString.Append("IRECTOR_ID], \r\n            T.CHIEF_DOCTOR_ID AS [PAT_VISIT.CHIEF_DOCTOR_ID], \r\n ");
            viewString.Append("           T.ATTENDING_DOCTOR_ID AS [PAT_VISIT.ATTENDING_DOCTOR_ID], \r\n         ");
            viewString.Append("   T.DOCTOR_IN_CHARGE_ID AS [PAT_VISIT.DOCTOR_IN_CHARGE_ID], \r\n            T.ADV");
            viewString.Append("ANCED_STUDIES_DOCTOR_ID AS [PAT_VISIT.ADVANCED_STUDIES_DOCTOR_ID], \r\n           ");
            viewString.Append(" T.PRACTICE_DOCTOR_ID AS [PAT_VISIT.PRACTICE_DOCTOR_ID], \r\n            T.PRACTIC");
            viewString.Append("E_DOCTOR_OF_GRADUATE_ID AS [PAT_VISIT.PRACTICE_DOCTOR_OF_GRADUATE_ID], \r\n       ");
            viewString.Append("     T.DEATH_DATE_TIME AS [PAT_VISIT.DEATH_DATE_TIME], \r\n            T.IN_CP_DAT");
            viewString.Append("E AS [PAT_VISIT.IN_CP_DATE], \r\n            T.IN_CP_USER_ID AS [PAT_VISIT.IN_CP_U");
            viewString.Append("SER_ID], \r\n            T.CP_STATUS AS [PAT_VISIT.CP_STATUS], \r\n            T.CP_");
            viewString.Append("ID AS [PAT_VISIT.CP_ID], \r\n            T.OUT_CP_DATE AS [PAT_VISIT.OUT_CP_DATE],");
            viewString.Append(" \r\n            T.IN_CP_DAYS AS [PAT_VISIT.IN_CP_DAYS], \r\n            T.THREE_DAY");
            viewString.Append("_OPERATION AS [PAT_VISIT.THREE_DAY_OPERATION], \r\n            T.ALERGY_DRUGS1 AS ");
            viewString.Append("[PAT_VISIT.ALERGY_DRUGS1], \r\n            T.INP_NO_ALIAS AS [PAT_VISIT.INP_NO_ALI");
            viewString.Append("AS], \r\n            T.CP_MEMO AS [PAT_VISIT.CP_MEMO], \r\n            T.CP_EXCLUDE_");
            viewString.Append("ID AS [PAT_VISIT.CP_EXCLUDE_ID], \r\n            T.CP_EXCLUDE_NAME AS [PAT_VISIT.C");
            viewString.Append("P_EXCLUDE_NAME], \r\n            T.CLINICAL_PATHWAY AS [PAT_VISIT.CLINICAL_PATHWAY");
            viewString.Append("], \r\n            T.PAT_ORIGIN AS [PAT_VISIT.PAT_ORIGIN], \r\n            T.X_CT_NO");
            viewString.Append(" AS [PAT_VISIT.X_CT_NO], \r\n            T.X_MRI_NO AS [PAT_VISIT.X_MRI_NO], \r\n   ");
            viewString.Append("         T.X_TUMOUR_CARD AS [PAT_VISIT.X_TUMOUR_CARD], \r\n            T.X_CONTAGI");
            viewString.Append("ON_CARD AS [PAT_VISIT.X_CONTAGION_CARD], \r\n            T.BA_VISIT_ID AS [PAT_VIS");
            viewString.Append("IT.BA_VISIT_ID], \r\n            T.PHONE_MAILING_ADDRESS AS [PAT_VISIT.PHONE_MAILI");
            viewString.Append("NG_ADDRESS], \r\n            T.X_Xshexian_NO AS [PAT_VISIT.X_Xshexian_NO], \r\n     ");
            viewString.Append("       T.dept_transfer AS [PAT_VISIT.dept_transfer], \r\n            T.ShuxuePinzh");
            viewString.Append("ong AS [PAT_VISIT.ShuxuePinzhong], \r\n            T.PAT_AGE AS [PAT_VISIT.PAT_AGE");
            viewString.Append("], \r\n            T.PAT_BIRTHDAY_BABY AS [PAT_VISIT.PAT_BIRTHDAY_BABY], \r\n       ");
            viewString.Append("     T.NURSE_GROUP_NO AS [PAT_VISIT.NURSE_GROUP_NO], \r\n            T.myID AS [PA");
            viewString.Append("T_VISIT.myID], \r\n            True AS _from0\r\n        FROM EF_EMRModelStoreContai");
            viewString.Append("ner.PAT_VISIT AS T\r\n    ) AS T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("EF_EMREntities.PAT_VISIT", viewString.ToString());
        }
    }
}
